baseurl: /
title: Mblog for Data Analysis
languageCode: en-us
paginate: '10'
theme: Mainroad
disqusShortname: ''
googleAnalytics: ''
Author:
  avatar: img/avatar.png
  bio: 
  name: Bohak Maeng
Params:
  authorbox: no
  description: 
  logo:
    subtitle: 
  opengraph: yes
  pager: yes
  post_meta:
    - date
    - categories
  readmore: no
  sidebar:
    home: right
    list: right
    single: right
    widgets:
      - search
      - recent
      - categories
      - taglist
  twitter_cards: no
  widgets:
    recent_num: 5
    tags_counter: no
